import 'bootstrap/dist/css/bootstrap.min.css';
import { Sora } from 'next/font/google'
import BootstrapClient from "@/components/bootstrapClient";
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SideBar from '@/components/sideBar';
import "./globals.css";

const soraFont = Sora({
  weight: ["300","400","500","600","700","800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="p-tbr" className={` ${soraFont.className}`}>
      <body className={`bg-dark ${soraFont.className} d-flex flex-column min-vh-100 vw-50`}>
        <BootstrapClient />
        {/* <Header /> */}
        <div className='d-flex flex-grow-1' style={{marginLeft: 250}}>
          <SideBar />
        {children}
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
